#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    fisherment-crew-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "fisherment-crew-redirectHttps"
    fisherment-crew-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "fisherment-crew-redirectHttps"
    fisherment-crew-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "fisherment-crew-redirectHttps"
    
    
    
    fisherment-crew-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-web-80"
      ruleSyntax: v3
      
      tls: true
      
    fisherment-crew-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    fisherment-crew-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^fisherment-crew\.ddev\.site$`)
      
      service: "fisherment-crew-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    fisherment-crew-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    fisherment-crew-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-fisherment-crew-web:80
        
    fisherment-crew-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-fisherment-crew-web:8025
        
    
    
    fisherment-crew-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-fisherment-crew-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/fisherment-crew.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/fisherment-crew.key