services:
  meilisearch:
    image: getmeili/meilisearch:v1.6
    environment:
      MEILI_MASTER_KEY: fishing-crew_dev_master_key
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
