# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontendApp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'                      # ili '20'
          cache: 'pnpm'
          cache-dependency-path: 'frontendApp/pnpm-lock.yaml'
      - run: corepack enable
      - run: corepack prepare pnpm@10.14.0 --activate
      - run: pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          extensions: sqlite, sqlite3, pdo_sqlite
      - run: composer install --no-interaction --prefer-dist --no-progress
      - name: Create .env and APP_KEY
        run: |
          cp .env.example .env || true
          php artisan key:generate --force
      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
        run: php artisan test --parallel
