name: CI
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install deps
        run: |
          composer install --no-interaction --prefer-dist
      - name: Lint
        run: ./vendor/bin/pint --test
      - name: Tests
        run:  php artisan test --parallel
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: cd frontendApp && pnpm install --frozen-lockfile
      - name: Build
        run: cd frontendApp && pnpm build
